% kmpc_setup.m
%
% Creates an instance of the kmpc class bases on user arguments.
% Must have a sysid class in the workspace for this to work

kmpc = kmpc( sysid ,...
        'horizon' , 25 ,...
        'input_bounds' , [ 0 , 10 ],... 
        'input_slopeConst' , [0.5e-2],... 
        'input_smoothConst' , [1e-1],... 
        'state_bounds' , [] ,...
        'cost_running' , 0.1 ,...
        'cost_terminal' , 100 ,...
        'cost_input' , 0 ); 